djangoProject1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("transcendence.urls")),
    path("admin/", admin.site.urls),
]

transcendence/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'transcendence'
urlpatterns = ([
    path('', views.main, name='main'),
    path("game_local/", views.game_local, name="game_local"),
    path("online_game/", views.online_game, name="online_game"),
    path("game/<uuid:room_number>/", views.game_room, name="game_room"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("tournaments/", views.tournaments, name="tournaments"),
    path("tournaments/create/", views.create_tournament, name="create_tournament"),
    path("tournaments/join/<int:pk>/", views.join_tournament, name="join_tournament"),
    path("tournaments/quit/<int:pk>/", views.quit_tournament, name="quit_tournament"),
    path("tournaments/delete/<int:pk>/", views.delete_tournament, name="delete_tournament"),
    path("profile/", views.profile, name="profile"),
    path("profile/logout/", views.logout_user, name="logout"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/delete/", views.delete_user, name="delete_user"),
    path("profile/<str:search_query>/", views.view_profile, name="view_profile"),
    path("search/", views.search, name="search"),
    path("uploadpdp/", views.uploadpdp, name="uploadpdp"),
    path("friends/", views.handle_friends, name="handle_friends"),
    path("friends/send_friend_request/<str:username>/", views.send_friend_request, name="send_friend_request"),
    path("friends/accept_friend_request/<int:request_id>/", views.accept_friend_request, name="accept_friend_request"),
    path("friends/decline_friend_request/<int:request_id>/", views.decline_friend_request, name="decline_friend_request"),
    path("friends/remove_friend/<int:friendship_id>/", views.remove_friend, name="remove_friend"),
    path('oauth2/authorize/', views.oauth2_authorize, name='oauth2_authorize'),
    path('oauth2/callback/', views.oauth2_callback, name='oauth2_callback'),
    path("ifoauth/<str:oauth_id>", views.ifoauth, name="ifoauth"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

transcendence/forms.py
from django import forms
from .models import Account, Tournament, Game
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm


class ChangePDPForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']
        if not avatar or avatar == 'avatars/default.png':
            raise forms.ValidationError("Veuillez télécharger une image.")

        if avatar.content_type not in ['image/jpeg', 'image/png', 'image/gif']:
            raise forms.ValidationError("Veuillez télécharger une image JPEG, PNG ou GIF.")
        return avatar


class PseudoIfOauthForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

    def clean_pseudo(self):
        pseudo = self.cleaned_data['username']
        if User.objects.filter(username=pseudo).exists():
            raise forms.ValidationError("Ce pseudo est déjà utilisé.")
        return pseudo


class CreateTournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = ['name']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']


class PasswordChangeCustomForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Ancien mot de passe'})
        self.fields['new_password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Nouveau mot de passe'})
        self.fields['new_password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirmer le nouveau mot de passe'})

transcendence/controllers.py
import math
import random
import time

from . import constants

paddle_speed = constants.PADDLE_SPEED
paddle_length = constants.PADDLE_LENGTH
paddle_width = constants.PADDLE_WIDTH
paddle_offset = constants.PADDLE_OFFSET
field_length = constants.FIELD_LENGTH
field_width = constants.FIELD_WIDTH
ball_radius = constants.BALL_RADIUS
ball_base_speed = constants.BALL_BASE_SPEED
ball_speed_inc = constants.BALL_SPEED_INCREASE
ball_max_speed = constants.BALL_MAX_SPEED
max_bounce_angle = constants.MAX_BOUNCE_ANGLE
client_fps = constants.CLIENT_FPS
server_fps = constants.SERVER_FPS


class PaddleController:
    x = 0
    y = 0
    z = 0
    player = "void"
    speed = paddle_speed
    score = 0
    cumul_dt = 0
    last_input_id = 0
    input_id = 0

    def addDt(self, dt):
        if (dt > 1 / client_fps):
            dt = 1 / client_fps
        if (dt < -1 / client_fps):
            dt = -1 / client_fps
        self.cumul_dt += dt

    def doMove(self):
        if (self.cumul_dt > 1 / server_fps):
            self.cumul_dt = 1 / server_fps
        if (self.cumul_dt < -1 / server_fps):
            self.cumul_dt = -1 / server_fps
        self.y += self.cumul_dt * self.speed
        self.cumul_dt = 0
        self.last_input_id = self.input_id
        if (self.y > field_width):
            self.y = field_width
        if (self.y < -field_width):
            self.y = -field_width


class BallController:
    x = 0
    y = 0
    z = 0
    speed = ball_base_speed
    start_angle = (random.random() - 0.5) * max_bounce_angle
    dx = math.cos(start_angle)
    dy = math.sin(start_angle)
    hit = 0
    cooldown = 1
    last_move = time.time()

    def doMove(self, p1, p2):
        delta_time = time.time() - self.last_move
        self.last_move = time.time()
        if self.cooldown > 0:
            self.cooldown -= delta_time
            return
        self.x += delta_time * self.speed * self.dx
        self.y += delta_time * self.speed * self.dy
        if (self.x + ball_radius > field_length - (paddle_offset + paddle_width / 2)
                and paddle_length / 2 + ball_radius > self.y - p1.y > -paddle_length / 2 - ball_radius
                and self.dx > 0):
            inter_pos = (self.y - p1.y) / (paddle_length + ball_radius)
            bounce_angle = inter_pos * max_bounce_angle
            self.dx = -math.cos(bounce_angle)
            self.dy = math.sin(bounce_angle)
            self.speed = min(ball_max_speed, self.speed + ball_speed_inc)
            self.hit = 0
        if (self.x - ball_radius < -field_length + (paddle_offset + paddle_width / 2)
                and paddle_length / 2 + ball_radius > self.y - p2.y > -paddle_length / 2 - ball_radius
                and self.dx < 0):
            inter_pos = (self.y - p2.y) / (paddle_length + ball_radius)
            bounce_angle = inter_pos * max_bounce_angle
            self.dx = math.cos(bounce_angle)
            self.dy = math.sin(bounce_angle)
            self.speed = min(ball_max_speed, self.speed + ball_speed_inc)
            self.hit = 0
        if ((self.y > field_width and self.dy > 0)
                or (self.y < -field_width and self.dy < 0)):
            self.dy = -self.dy
        if self.x > field_length:
            self.x = 0
            self.y = 0
            p2.score += 1
            self.speed = ball_base_speed
            self.cooldown = 1
        if self.x < -field_length:
            self.x = 0
            self.y = 0
            p1.score += 1
            self.speed = ball_base_speed
            self.cooldown = 1

transcendence/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseNotAllowed, HttpResponseForbidden, \
    JsonResponse
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as login_p, logout, update_session_auth_hash
from django.db.models import Q
from django.contrib.auth.models import User
from .models import Account, Friendship, Tournament, Game
from django.contrib import messages
from oauth2_provider.views import ProtectedResourceView
from .forms import ChangePDPForm, PseudoIfOauthForm, CreateTournamentForm, UserProfileForm, PasswordChangeCustomForm
from django.contrib.auth.decorators import login_required
from oauth2_provider.views import AuthorizationView, TokenView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.shortcuts import redirect
import requests
import random
import re


# Create your views here.

@login_required(login_url='transcendence:login')
def main(request):
    return render(request, 'transcendence/main.html')


@login_required(login_url='transcendence:login')
def index(request):
    context = {"accounts": User.objects.all()}
    return render(request, "transcendence/index.html", context)


@login_required(login_url='transcendence:login')
def game_local(request):
    context = {"accounts": User.objects.all()}
    return render(request, "transcendence/game_local.html", context)


@login_required(login_url='transcendence:login')
def online_game(request):
    acc = Account.objects.get(user=request.user)
    game = Game.objects.filter(Q(player1=acc) | Q(player2=acc), status="started").first()
    latest_game = Game.objects.filter(created_for_queue=True, status="wait").order_by('-id').first()
    game_id = None
    if game:
        game_id = game.id
    elif latest_game:
        latest_game.player2 = acc
        latest_game.save()
        game_id = latest_game.id
    else:
        acc = Account.objects.get(user=request.user)
        game = Game(created_for_queue=True, player1=acc)
        game.save()
        game_id = game.id
    return HttpResponse(game_id)


@login_required(login_url='transcendence:login')
def game_room(request, room_number):
    acc = Account.objects.get(user=request.user)
    try:
        game = Game.objects.get(pk=room_number)
    except Game.DoesNotExist:
        raise Http404("Game does not exist")
    if game.player1 != acc and game.player2 != acc:
        return HttpResponseForbidden("you are not allowed here")
    return render(request, "transcendence/game_room.html")


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            account = Account(user=user)
            account.save()
            login_p(request, user)
            return redirect("transcendence:main")
    else:
        form = UserCreationForm()
    return render(request, "transcendence/register.html", {"form": form})


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login_p(request, user)
            return redirect("transcendence:main")
        else:
            messages.info(request, "Wrong login or password")

    form = AuthenticationForm()
    return render(request, "transcendence/login.html", {"form": form})


@login_required(login_url='transcendence:login')
def leaderboard(request):
    context = {"accounts": Account.objects.all().order_by("-score")}
    return render(request, "transcendence/leaderboard.html", context)


@login_required(login_url='transcendence:login')
def profile(request):
    try:
        acc = Account.objects.get(user=request.user)
    except Account.DoesNotExist:
        return HttpResponse("an error that shouldn't happen, happened")
    return render(request, "transcendence/profile.html", {"account": acc})


@login_required(login_url='transcendence:login')
def logout_user(request):
    logout(request)
    return redirect("transcendence:main")


@login_required(login_url='transcendence:login')
def search(request):
    search_query = request.GET.get('search_query')
    if search_query:
        context = {"accounts": User.objects.filter(username__icontains=search_query)}
        return render(request, "transcendence/search.html", context)
    else:
        context = {"accounts": User.objects.all()}
        return render(request, "transcendence/search.html", context)


@login_required(login_url='transcendence:login')
def tournaments(request):
    tournamentss = Tournament.objects.all()
    acc = Account.objects.get(user=request.user)
    return render(request, "transcendence/tournaments.html", {"tournaments": tournamentss, "account": acc})


@login_required(login_url='transcendence:login')
def create_tournament(request):
    if request.method == "POST":
        form = CreateTournamentForm(request.POST)
        if form.is_valid():
            acc = Account.objects.get(user=request.user)
            tournament = form.save(commit=False)
            tournament.admin = acc
            tournament.save()
            tournament.users.add(acc)
            return JsonResponse({'success': True, 'message': "Tournament created", 'id': tournament.id})
        else:
            return JsonResponse({'success': False, 'message': "form isnt valid"})
    form = CreateTournamentForm()
    return render(request, "transcendence/create_tournament.html", {"form": form})


@login_required(login_url='transcendence:login')
def join_tournament(request, pk):
    if request.method == "POST":
        tournament = get_object_or_404(Tournament, pk=pk)
        account = get_object_or_404(Account, user=request.user)

        if tournament.users.count() >= 4:
            return JsonResponse(
                {"success": False, "message": "This tournament already has the maximum number of participants."})
        tournament.users.add(account)
        if tournament.users.count() == 4:
            tournament.islaunched = True
            users = list(tournament.users.all())
            random.shuffle(users)
            pair1 = (users[0], users[1])
            pair2 = (users[2], users[3])
            game1 = Game.objects.create(player1=pair1[0], player2=pair1[1], status="wait",
                                        linked_tournament=tournament)
            game2 = Game.objects.create(player1=pair2[0], player2=pair2[1], status="wait",
                                        linked_tournament=tournament)
            tournament.stage1games.add(game1, game2)
            tournament.save()
        return JsonResponse({"success": True, "message": "successfully joined tournament"})
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required(login_url='transcendence:login')
def quit_tournament(request, pk):
    if request.method == "POST":
        tournament = get_object_or_404(Tournament, pk=pk)
        account = get_object_or_404(Account, user=request.user)
        if not tournament.islaunched:
            tournament.users.remove(account)
            return JsonResponse({'success': True})
        return JsonResponse({'success': False, "message": "failed to quit tournament"})
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required(login_url='transcendence:login')
def delete_tournament(request, pk):
    if request.method == "POST":
        tournament = get_object_or_404(Tournament, pk=pk)
        if tournament.admin.user == request.user and not tournament.islaunched:
            tournament.delete()
            return JsonResponse({"success": True, "message": "tournament deleted"})
        return JsonResponse({"success": False, "message": "tournament could not be deleted"})
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required(login_url='transcendence:login')
def view_profile(request, search_query):
    user = get_object_or_404(User, username=search_query)
    try:
        acc = Account.objects.get(user=user)
    except Account.DoesNotExist:
        return HttpResponse("an error that shouldn't happen, happened")
    ranking = Account.objects.filter(score__gt=acc.score).count() + 1
    victories_count = Game.objects.filter(winner=acc).count()
    defeat_count = Game.objects.filter(
        (Q(player1=acc) | Q(player2=acc)) & ~Q(winner=acc) & Q(status="finished")
    ).count()
    games = Game.objects.filter((Q(player1=acc) | Q(player2=acc)) & Q(status="finished"))
    is_in_game = Game.objects.filter(
        (Q(player1=acc) | Q(player2=acc)) & Q(status="started")
    ).exists()
    return render(request, "transcendence/view_profile.html",
                  {"account": acc, "ranking": ranking, "victories": victories_count, "defeats": defeat_count,
                   "games": games, "isingame": is_in_game})


@login_required(login_url='transcendence:login')
def edit_profile(request):
    try:
        acc = Account.objects.get(user=request.user, oauth2_id=None)
    except Account.DoesNotExist:
        acc = None
    print("here acc ", acc)
    if request.method == 'POST':
        user_form = UserProfileForm(request.POST, instance=request.user)
        password_form = PasswordChangeCustomForm(request.user, request.POST)

        if user_form.is_valid():
            user_form.save()
            if user_form.has_changed():
                print("hey")
                return JsonResponse(
                    {"success": True, "message": 'Pseudo successfully edited'})

        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)

transcendence/templates/transcendence/create_tournament.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'transcendence/mark_online.js' %}"></script>
    <link rel="stylesheet" href="{% static 'transcendence/css/login.css' %}">
</head>
<body>
    <div class="login-container">
        <h2>Create a tournament</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        
            <button type="submit" class="btn-submit">Submit</button>
        </form>
    </div>

</body>
</html>

transcendence/templates/transcendence/friends.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friends</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/friends.css' %}">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <section>
                <h1>Friends list</h1>
                <ul id="friend-list">
                    {% for friend in friends_list %}
                        <li>
                            <a href="#view_profile?{{ friend.0.user.username }}">
                                {{ friend.0.user.username }}
                            </a>
                            <button class="remove-friend-btn" id="friend-{{ friend.1 }}" onclick="remove_friend('{{ friend.1 }}')">Remove friend</button>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
        <div class="col-md-6">
            <section>
                <h1>Pending friends list</h1>
                <ul id="request-list">
                    {% for friend_request in pending_requests %}
                        {% if request.user != friend_request.from_user.user %}
                            <li id="friend-request-{{ friend_request.id }}">
                                {{ friend_request.from_user.user.username }}
                                <form method="post"
                                      action="{% url 'transcendence:accept_friend_request' friend_request.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="request_id" value="{{ friend_request.id }}">
                                    <button type="submit" onclick="accept_friend(event, {{ friend_request.id }}, '{{ friend_request.from_user.user.username }}')">Accept</button>
                                </form>
                                <form method="post"
                                      action="{% url 'transcendence:decline_friend_request' friend_request.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="request_id" value="{{ friend_request.id }}">
                                    <button type="submit" onclick="decline_friend(event, {{ friend_request.id }})">Decline</button>
                                </form>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section>
        </div>
    </div>
</div>

{% comment %} <script>
    document.addEventListener("DOMContentLoaded", function () {
        const removeButtons = document.querySelectorAll('.remove-friend-btn');
        removeButtons.forEach(button => {
            button.addEventListener('click', function () {
                const friendshipId = this.getAttribute('data-id');
                fetch(`/friends/remove_friend/${friendshipId}/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({'friendship_id': friendshipId})
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            this.parentElement.remove();
                        } else {
                            alert('Failed to remove friend: ' + data.error);
                        }
                    })
                    .catch(error => console.error('Error:', error));
            });
        });
    });
</script> {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

transcendence/templates/transcendence/game_room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Game Room</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/main.css' %}">
    <style>
        .container {
            margin: 0 auto;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        body {
            background: #1a1a1a;
        }

        .gameFrame {
            width: 1500px;
            height: 800px;
        }

		#score1 {
			image-rendering: 'pixelated';
		}
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontfaceobserver/2.1.0/fontfaceobserver.standalone.js"></script>
</head>
<body>
<div class="row justify-content-center">
    <div class="col-md-6" style="width: 1000px; height: 800px;">
        <div id="pongCanvasOnline" class="container rounded p-4" style="background: #ffcc00; margin-top: 10px; width: 900px; height: 700px; image-rendering: pixelated"></div>
    </div>
</div>
</body>
</html>

transcendence/templates/transcendence/ifoauth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Connection</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/login.css' %}">
</head>
<body>
<div class="login-container">
    <h2>Connection to Transcendence</h2>
    <form method="POST">
        <p> Username already taken please use another one</p>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-submit">Connection</button>
    </form>
</body>
</html>

transcendence/templates/transcendence/leaderboard.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaderboard</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/leaderboard.css' %}">
    <script src="{% static 'transcendence/mark_online.js' %}"></script>
</head>
<body>
<div class="content">
    <div class="leaderboard-container">
        <h2>Leaderboard</h2>
        <ul class="leaderboard-list">
            {% for account in accounts %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>{{ forloop.counter }}</span>
                    <span><a href="#view_profile?{{ account.user.username }}">{{ account.user.username }}</a></span>
                    <span>Score : {{ account.score }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
</body>
</html>

transcendence/templates/transcendence/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'transcendence/css/login.css' %}">
</head>
<body>
    <div class="login-container">
        <h2>Connection to Transcendence</h2>
        <form action="/login/" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-submit">Connection</button>
            <p>Don't have an account ? <a href="/register/">Register</a></p>
        </form>
        <a href="{% url 'transcendence:oauth2_authorize' %}">Login with OAuth2</a>
    </div>
    
</body>
</html>

transcendence/templates/transcendence/privacy-policy.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Privacy Policy</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/main.css' %}">
</head>
<body>
<p>This web application complies with GDPR.</p>
<p>We process your data such as: your profile photo, your username, and your game history.</p>
<p>We do not have any partners and we do not offer advertisements. We do not use any tracking cookies. This allows us not to have a cookie banner.</p>
<p>To delete your data, simply delete your account by clicking on profile at the top right. Your data will then be anonymized.</p>
<p>For any questions, contact us by email: oizel.alexis@gmail.com</p>
</body>
</html>

transcendence/templates/transcendence/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile - Transcendence</title>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'transcendence/css/profile.css' %}">
    <script src="{% static 'transcendence/mark_online.js' %}"></script>
</head>
<body style="background: #e9e4e4e3">
<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="{{ account.avatar.url }}" class="profile-img" alt="...">
                <div class="card-body">
                    {% if user.is_authenticated %}
                        <h5 class="card-title">Pseudo: {{ user.username }}</h5>
                    {% else %}
                        <h5 class="card-title">Pseudo: default</h5>
                    {% endif %}
                    <p class="card-text">Score: {{ account.score }} points</p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Options</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><a onclick="edit_profile()">Edit your information</a></li>
                        <li class="list-group-item"><a onclick="uploadpdp()">Change the profile picture</a></li>
                        <li class="list-group-item"><a href="{% url 'transcendence:logout' %}">Sign out</a></li>
                        <li class="list-group-item">
                            <button style="all: unset" id="delete_button">Delete account</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    {% comment %} const button = document.getElementById("delete_button");
    button.addEventListener('click', function () {
        fetch('/profile/delete/', {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/json'
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    window.location.href = '/register/';
                } else {
                    alert('Failed to delete account: ' + data.error);
                }
            })
            .catch(error => console.error('Error:', error));
    }); {% endcomment %}
</script>
</body>
</html>

transcendence/templates/transcendence/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/register.css' %}">
</head>
<body>
    <div class="register-container">
        <h2>Registration for Transcendence</h2>
        <form action="/register/" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-submit">Register</button>
            <p>Already have an account ? <a href="/login/">Login</a></p>
        </form>
    </div>
</body>
</html>

transcendence/templates/transcendence/search.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Search results - Transcendence</title>
    <link rel="stylesheet" href="{% static 'transcendence/css/search.css' %}">
    <script src="{% static 'transcendence/mark_online.js' %}"></script>
</head>

<body>
<div class="container mt-5">
    <h1 class="mb-4">Search results</h1>
    {% for account in accounts %}
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col">{{ account.username }}</div>
                    <div class="col text-end">
						<a href="#view_profile?{{ account.username }}" class="btn btn-primary">See profile</a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>

</body>
</html>